### ISSUE TITLE
서버 관련돼서 질문드립니다.

### ISSUE THREAD

**Issue by seo-jinBro** [lgewst/SNU#2]
주임님 안녕하세요.
서버 관련된 부분을 제가 하려고 공부를 하면서 진행하고 있는데,
js 관련된 부분을 완전 처음해서 그 부분부터 공부하느라 진도가 조금느리지만...

현재까지 제가 이해한 부분이 맞는지 여쭤보고 싶어서 질문드립니다.

우선 milenet/README.md 에서 실행방법에 4번을 보면 

웹소켓 연결 주소 수정이 필요하다고 하셨는데, milenet.js가 아니라 mindless.js의 socket연결 코드 부분을 말씀하시는 것 맞나요?

그리고 README.md의 아래 링크 부분에서,

 MILENET URL (ws://mile.cafe24app.com?id~~)는 Node.js 실행환경을 구축하지않아도 쓸 수 있다고 말씀하셨는데 저희도 쓸 수 있다는 말씀이신가요?

 그리고 MileNet 서비스 연결 및 활용을 웹앱이 아니라 Mindless Framework에서 해야한다는 말씀은 html에 그대로 올리는 JSP & Servelet 같은 것 말고, index.html에서처럼 <script src = "mindless.js"><\script> 처럼 이를 기반으로 연결하라는 것 맞나요?
(그래서 게임 통신에 추가로 필요한 부분들은 mindless.js에 제가 직접 추가해서 쓰라는 것 맞나요?)

끝으로, 연휴 잘보내시길 바랍니다! 막바지에 올려서 죄송합니다 ㅠㅠ (처음에 js랑 기본적인 서버들을 보느라... ㅠㅠㅠㅠㅠ )

**Comment by seo-jinBro** [comment]
추가적으로, 실제로  mileurl.com/demo 에서 실행을 하는데, index.html 에도 MILE 객체가 디폴트로 가지는 appurl이 mileurl.com/demo 인 이유도 이 때문이라는 것은 이해했습니다. 웹소켓 연결주소를 바꾸라는 말씀이 이 주소를 나타낸다고 생각하는데, 혹시 이 주소는 어떻게 관리하나요? 임의로 할당한것은 아니라고 생각하는데, 그렇다면 어떻게 주소를 만들어주고 이를 관리하나요..? ㅠㅠ 생 초짜라 질문이 많아서 죄송합니다

**Comment by anawhj** [comment]
질문 언제든 환영입니다. 홍지혜 주임이 휴가 중이라 대신 답변 남깁니다.

1. 웹 소켓 연결 구문은 언급한 바와 같이 mindless.js의 socket 연결 코드가 맞습니다. 해당 부분 수정했습니다.
2. ws://mile.cafe24app.com에서 현재 MileNet 서비스가 실행되고 있습니다. 이에 별도로 Node.js 기반 서버를 구축할 필요 없이 이것을 사용해도 괜찮습니다. (혹 사용하다가 에러 또는 문제 발생 시 바로 알려주세요. 기본적으로는 처음 접속에는 URL 출력 화면이, 두 번째 이상 접속 시에는 연결된 앱 화면이 출력되는 것이 정상 동작입니다.)
3. 웹 앱에서는 MILE 객체를 통해 공개된 API(e.g. MILE.init, MILE.setAppId)만을 사용하여야 합니다. 다시
 말해 웹 앱에서는 직접 MileNet 서비스에 연결하지 않고 단지 mindless.js를 script 태그를 통해 불러오고
 MILE.init() 함수 실행만으로 연결 부분을 처리하여야 한다는 의미입니다. Mile과 별개로 웹 앱의 기능을 위해 JSP나 Servlet을 활용하는 것은 얼마든지 가능합니다. 그리고 특별한 이슈가 있지 않는 한 mindless.js는 수정하지 않습니다. (버그 발견 시 이슈에 올려주거나 버그를 수정해서 올려주세요.)
4. mileurl.com/demo는 샘플 앱 동작 확인을 위한 참고로만 활용하고, 실제 개발 중인 앱을 올리는 서버는 직접 로컬피씨 또는 클라우드 서비스를 통해 구축해야 합니다. (아파치, 톰캣, 노드, 서블릿, AWS 등 많은 방법이 있습니다.) 참고로 https://www.cafe24.com에서 월 500원에 400M 한도로 호스팅 서비스 이용이 가능합니다.
5. 만약 본인 PC 또는 노트북에 웹 서버를 직접 구축해서 테스트하는 경우라면, 웹 앱 실행을 위한 URL이 http://localhost:8080/game 과 같이 될 수 있으며, 이런 경우에는 MILE.setAppURL(DEFAULT_LINK);의 파라미터에 해당 URL을 string 타입으로 기재하면 됩니다. (실제 mindless.js에서 처리할 떄는 임의의 키 생성을 위한 식별자로 사용될 뿐 값 자체에는 큰 의미가 있지 않습니다. 즉, setAppURL 함수의 파라미터에
 abcd와 같이 넣어도 동작에 에러가 발생하지 않습니다.)
6. 이렇게 저렇게 해보고 시행착오도 경험하는 과정에서 많은 학습 효과가 있을 것으로 예상됩니다. 개념 이해를 먼저 해보면 더 빠른 진행이 가능합니다.

**Comment by seo-jinBro** [comment]
송효진 주임님 정말 감사드립니다!
궁금증이 어느정도 해결된것같습니다. (더 시행착오를 겪도록하겠습니다 ㅎㅎㅎㅠㅠㅠ)
궁금한 점은 이슈로 많이 여쭤보도록 하겠습니다.
감사합니다

**Comment by jihyerish** [comment]
제가 자리를 비운 동안 송효진 선임님께서 답변을 잘 해주셨네요 : )
궁금한 내용 올리시면 신속히 피드백 줄게요~
이슈로 질문 올려줘도 보기 편하네요ㅎㅎ
