### ISSUE TITLE
웹소켓 관련해서 질문드립니다.

### ISSUE THREAD

**Issue by seo-jinBro** [lgewst/SNU#3]
주임님 안녕하세요.

지금 현재 http://localhost:8001 에서 작업하고 있습니다.

저희가 공유화면과 개별 사용자 모바일 화면을 분리해서 작성하고자하는데, 주신 milenet.js 파일에서
io.on('connection', function (socket) { }); 에서 궁금증이 있습니다.
제가 이해한 바로는, 지금 http를 8001번 포트를 사용하니까 http://localhost:8001일때 on이라고 생각했는데,
http://localhost:8001/connect (원래파일에서는 mileurl.com/demo)를 들어가야 on에 해당하는 log가 찍혀서 어떻게 돌아가는지 잘 모르겠어서 질문을 드립니다.. ㅠㅠ

질문이 약간 정리가 안되고 두서없어서 죄송합니다.

지금 목표는, connect에 있는 index.html로 들어가면 (공유화면)
url을 만들어서 뿌려주고 사용자가 해당 url로 들어가면, mobile/index.html로 redirect되어서
연결이 되도록 하고싶습니다. (즉 같은 connect/index.html 로 들어가야 연결이 아니고, mobile/index.html로 들어가야 연결. 즉,  connect/index.html 과(공유화면) mobile/index.html 로 들어간 애들끼리의 (유저들) 연결)

현재는 connect/index.html 들 끼리 연결이 되는데, 이를 바꾸는 방법을 혹시 여쭤봐도 될까요?

그리고 mindless.js의 init관련된 코드에서, socket = new  io.connect(ws:~~) 로 되어있는 부분을
웹소켓 주소 ws:cafe.~~ 대신에 저희가 쓰는 localhost:8001?id=~ 이런식으로 쿼리를 넘겨주는 애까지 연결하면 되는 것 맞나요?

(얘를 localhost:8001/connect 라든지 localhost:8001/mobile로 바꾸면 안되더라구요... 제가 코드 이해가 아직 부족한 것 같습니다.)

**Comment by jihyerish** [comment]
> 제가 이해한 바로는, 지금 http를 8001번 포트를 사용하니까 http://localhost:8001일때 on이라고 생각했는데,
http://localhost:8001/connect (원래파일에서는 mileurl.com/demo)를 들어가야 on에 해당하는 log가 찍혀서 어떻게 돌아가는지 잘 모르겠어서 질문을 드립니다.. ㅠㅠ

올려주신 코드를 보면, index.html (https://github.com/lgewst/SNU/blob/mobile/bang/connect/index.html)
은 connect 디렉토리에 있으며
milenet.js 파일은 connect의 상위 디렉토리에 위치해있습니다.
"node milenet" 명령어로 Node를 실행시키면 milenet.js 파일이 위치한 곳이 Root가 됩니다.

connection을 하는 부분은 index.html의 MILE.init();를 통해 io.on('connection', function (socket) { });를 실행하여 이루어집니다.
따라서 index.html이 위치한 경로를 따라서  http://localhost:8001/connect 로 해야지만 connection에 대한 log가 찍히게 됩니다.

**Comment by jihyerish** [comment]
> 지금 목표는, connect에 있는 index.html로 들어가면 (공유화면)
url을 만들어서 뿌려주고 사용자가 해당 url로 들어가면, mobile/index.html로 redirect되어서
연결이 되도록 하고싶습니다. (즉 같은 connect/index.html 로 들어가야 연결이 아니고, mobile/index.html로 들어가야 연결. 즉, connect/index.html 과(공유화면) mobile/index.html 로 들어간 애들끼리의 (유저들) 연결)
현재는 connect/index.html 들 끼리 연결이 되는데, 이를 바꾸는 방법을 혹시 여쭤봐도 될까요?

그렇게 하려면, mobile 디렉토리의 index.html에도 MILE.init();을 추가해주세요.
디버깅 내용도 보려면 MILE.showDebug(true);도 추가해야겠죠?ㅎㅎ

eg)
`<script type="text/javascript">
        window.addEventListener("load", function() {
                MILE.setAppID("mobile");
                MILE.setAuthor("snu");
                MILE.setVersion("0.1");
                MILE.showMileURL(false);
                MILE.showDebug(true);
                MILE.init();
                }
                )
        </script>
`

**Comment by jihyerish** [comment]
> 그리고 mindless.js의 init관련된 코드에서, socket = new io.connect(ws:) 로 되어있는 부분을
웹소켓 주소 ws:cafe. 대신에 저희가 쓰는 localhost:8001?id=~ 이런식으로 쿼리를 넘겨주는 애까지 연결하면 되는 것 맞나요?

네, 맞게 한 것 같은데, 어떤 상황에서 문제가 있는 거에요?
위에 코멘트 드린 내용 참고해서 수정해도 해결이 되지 않으면 문제가 되는 상황을 좀더 풀어서 설명해줄 수 있어요?

**Comment by seo-jinBro** [comment]
주임님 답변 감사합니다. 제가 늦게봐서 늦게 다시 질문을 올리게 되어 죄송합니다.
제가 현재 이해가 잘 안되는 부분은, mindliess.js에서 소켓의 new io.connect 뒤의 주소가 지금 현재

http://147.47.249.199:8001?id=" + MILE.appid + "&author=" + MILE.author + "&version=" + MILE.version + "&appurl=" + MILE.appurl

로 되어있는데, 실제 연결이 connect/index.html 끼리만 되는 부분입니다. 

mobile/index.html 에도 MILE.init()을 넣어줘서 연결이 되야한다고 생각하는데,
 connect/index.html 끼리는 연결이 되는데, 
(즉, 로컬에서 테스트한다고 하면 두개의 브라우저에 localhost:8001/connect 로 들어가면 각각 연결됨)
mobile/index.html 은 connect/index.html과 연결이 되지 않는 부분을 잘모르겠어서 질문을 드립니다.

지금 질문을 드리면서 든 생각은 혹시 리다이렉트를 하면 MILE.init()이 실행이 되지 않아서 그런것인가요?

init: function() {
    // Web Socket Init
    // socket = new io.connect("ws://mile.cafe24app.com?id=" + MILE.appid + "&author=" + MILE.author + "&version=" + MILE.version + "&appurl=" + MILE.appurl);
    socket = new io.connect("http://147.47.249.199:8001?id=" + MILE.appid + "&author=" + MILE.author + "&version=" + MILE.version + "&appurl=" + MILE.appurl);
    // socket = new io.connect("http://localhost:8001?id=" + MILE.appid + "&author=" + MILE.author + "&version=" + MILE.version + "&appurl=" + MILE.appurl);

    // console.log('socket connection in mindless.js');

    socket.on("connect", function() {
      MILE.log("$mile_init", "success");
    });
    // A message is arrived from the server
    socket.on("message", function(msg){
      console.log(msg);
      MILE.MileHandler(msg.type, msg.data, msg.from);
    });
    MILE.showMileStatus(true);
  },

**Comment by seo-jinBro** [comment]
주임님 혹시 다음 주 중에 만나뵙고 여쭤봐도 될까요?

개인적으로 서버 관련돼서 많이 여쭤봐야할 것 같아서 혹시 괜찮으시다면 만나뵙고 질문 드리고 싶습니다.

바쁘실텐데 여쭤봐서 죄송합니다 !!

**Comment by seo-jinBro** [comment]
말씀하신 부분 제가 코드를 잘못쳤었어서 안되는 부분이었습니다 !! 감사합니다 ㅠ

**Comment by jihyerish** [comment]
> 주임님 혹시 다음 주 중에 만나뵙고 여쭤봐도 될까요?

네, 괜찮아요. 이번 주 중에 시간 조율해봐요~
