### ISSUE TITLE
서버 관련해서 질문드립니다.

### ISSUE THREAD

**Issue by seo-jinBro** [lgewst/SNU#4]
자꾸 질문을 많이드려 죄송합니다 ㅠㅠ

지금 현재 제 기숙사 공유기 네트워크에 제 노트북으로 서버를 돌리는데, 
다른 사람이 작업한 내용이 제 노트북에 반영이 되지 않아서 실시간으로 확인하기 어려운 문제가 있습니다.

찾아보니 가상 서버를 이용한다고 되어있는데, 이를 구축하기 위한 방법 중 혹시 좋은 방법 추천해주실 수 있나요?

**Comment by jihyerish** [comment]
다른 학생들이 작업한 내용 공유를 어떻게 하고 있어요?

가상 서버를 이용하는 이유가 작업 내용 실행이 아닌 작업 내용 공유라면, Github을 이용해도 괜찮을 것 같아서요~
