### ISSUE TITLE
주임님 아까 질문 못드렸던 것이 있는데 궁금해서 여쭤보고싶습니다.

### ISSUE THREAD

**Issue by seo-jinBro** [lgewst/SNU#5]
주임님 안녕하세요!

저희가 알고리즘을 java로 돌리고 싶은데, node.js 환경 하에서 java를 돌리는 법이 있을까요..?

찾아보면 node-java 브릿지 같은게 나오는데, 얘는 js에서 java를 import 시켜서 쓸 수 있도록 하는 툴인 것 같습니다.

그런데, 제가 이해한 바로는 자바스크립트가 클라이언트 단에서 수행되는 것으로 알고있어서 이걸 쓰게 되면 개별 클라이언트 단에서 게임 로직을 전부 돌려버린다고 생각되어 의도와 맞지 않다고 생각되는데, 혹시 java 를 다른 방법으로 쓸 수 있는 방법이 있을까요..?

js로 다 다시 짜려고 해도, 위의 문제가 똑같이 발생할 것 같아서 궁금해서 여쭤보고싶습니다.

주신 스펙에서 node.js를 이용하라고 하셔서 지금 톰캣이나 다른 WAS를 쓰는 방안은 전부 배제하고 있는데, 
서버에서 직접 게임 알고리즘을 돌리고 싶은데 어떻게 해결할 수 있을지 여쭤보고싶습니다!

아까 만나뵙고 여쭤봤어야하는데 제가 정신이 없어서 미쳐 못 여쭤본 점 죄송합니다 !!! ㅠ

**Comment by jihyerish** [comment]
이런.. 이 이슈올린 것 지금 발견했어요
이 문제 해결 됬나요?
