### ISSUE TITLE
MILE.send()가 여러번 전송되는 문제가 있습니다.

### ISSUE THREAD

**Issue by yuzzyuzz** [lgewst/SNU#6]
안녕하세요 주임님
MILE사용에 있어서 문제가 발생하는데 이게 html이나 다른 문제인지 mile의 문제인지 확인이 안 되어서 이슈에 올립니다.
현재 mobile/mobile_index.html에서 보시면 button이나 카드 이미지를 누르면 필요한 정보를 받아 새로운 페이지를 꾸미기 위해 MILE.send()로 리퀘스트를 보내는데요,
처음에 한 번 누르는 것은 send가 한번만 가는데, 그 다음에는 계속해서 2번, 3번, 이런식으로 여러번 리퀘스트를 보내더라구요
예를 들면, other players를 누른 뒤 다른 플레이어 클릭 -> (리퀘스트 1번 보내짐)-> 다른 플레이어의 기본 정보가 페이지로 띄워짐 -> back버튼 클릭->(리퀘스트 한 번 보내짐) -> 백그라운드 페이지로 돌아감 -> 다시 other players의 다른 플레이어 클릭 -> (리퀘스트 2번)
이런 방식으로 리퀘스트의 개수가 증가하는 문제가 있습니다.
혹시 MILE의 문제인지 확인해주실 수 있나요?
감사합니다.
 
![image](https://user-images.githubusercontent.com/13999310/26917874-d85b7c3c-4c6a-11e7-9675-22e26c674ec6.png)

**Comment by Dongjoo-Kim** [comment]
HTML 문제인 것을 발견하여 해결하였습니다.
